name: Push To DockerHub
on:
  push:
    branches:
      - master
      - main

env:
  DOCKERHUB_USERNAME: zibdie
  OFFICIAL_TAG: zibdie/telegram-pronunciationbot:latest
  MAIN_REPO_NAME: zibdie/telegram-pronunciationbot
  DOCKERFILE_PATH: /

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          file: ${{ env.GITHUB_WORKSPACE }}/Dockerfile
          push: true
          tags: ${{ env.OFFICIAL_TAG }}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ env.MAIN_REPO_NAME }}
          readme-filepath: ./readme.md
